// <auto-generated />
using System;
using Atalhos.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atalhos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410181902_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Atalhos.Models.AliasModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AmbienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DbName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DbProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DbServer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DbType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("JobServerEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JobServerLocalOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobServerMaxThreads")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JobServerProcessPoolEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RunService")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaDB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Servidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sgbd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioDB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("Aliases");
                });

            modelBuilder.Entity("Atalhos.Models.AmbienteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ControlaIIS")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favorito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ambientes");
                });

            modelBuilder.Entity("Atalhos.Models.AliasModel", b =>
                {
                    b.HasOne("Atalhos.Models.AmbienteModel", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambiente");
                });
#pragma warning restore 612, 618
        }
    }
}
